server:
  port: 8081

spring:
  application:
    name: midterm

  datasource:
    url: jdbc:postgresql://localhost:5432/db1
    username: user
    password: 123

  jpa:
    hibernate:
      ddl-auto: none

  kafka: 
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      # retries: 3  # Số lần retry khi gửi thất bại, comment vi khi
      # bat enable.idempotence thi retries = Integer.MAX_VALUE
      properties:
        # Đảm bảo không gửi duplicate message
        enable.idempotence: true
        # So request gui song song, nhung kafka tu set = 5 khi co enable.idempotence
        # max.in.flight.requests.per.connection: 5
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: consumer-group-1
      # Khong nen dung vi consumer se doc lai tat ca message
      # auto-offset-reset: earliest
      properties:
        # Nguy hiem khi len production, cho phép deserialize tất cả các package
        spring.json.trusted.packages: "*"
jwt:
  secret: gsdg9824tgwnau81039p2o3tgrnewjfvshdua8oi24kgqewihod
  expiration_access: 36000000 # milliseconds, tinh ra la = 15 * 60 * 1000
  expiration_refresh: 604800000 # milliseconds, tinh ra la = 7 * 24 * 60 * 1000

recaptcha:
  secret: 6LdYXDAsAAAAAGdpKMehnyORcHKi3_P72u_UMiMB
  verify-url: https://www.google.com/recaptcha/api/siteverify

otp:
  expiry-minutes: 600

